### ISSUE TITLE
Support for []=

### ISSUE THREAD

**Issue by sdalu** [tbuehlmann/dry-struct-setters#4]
It is possible to set a value using `obj.attr = val`, it would be nice to also support `ob[attr] = val` as both `obj.attr` and `obj[attr]` return a value

**Comment by tbuehlmann** [comment]
Sounds reasonable, implemented in f7fc8bafe7fdd7d49cb58ebbf0f597b0fcf270e5. I didn't touch the repo in a while and saw that `Dry::Types` changed a little, so I fixed that while I was on it. There's a `>= 1.4.0` requirement present now.

0.4.0 pushed to rubygems.
